random_generator:
  train_n: 60
  test_n: 1000
  J: 4
  I: 12
  p: 0.9
  lam_r: 2.0
  lam_w: 5.0
  c: [-14, -9, -20, -15, -4, -40, -20, -15, -15, -8, -9, -24]
  M: 1000
  epochs: 30
  seed: 2349

  # Intervals for regular regime
  h_int_r: [5000, 6000]
  q_ints_r:
    - [6, 8]
    - [6, 8]
    - [6, 8]
    - [6, 8]
  w_ints_r:
    - [0.8, 1]
    - [0.8, 1]
    - [0.9, 1]
    - [0.8, 1]

  # Intervals for extreme regime
  h_int_w: [500, 600]
  q_ints_w:
    - [15, 18]
    - [15, 18]
    - [18, 20]
    - [14, 16]
  w_ints_w:
    - [0.5, 0.6]
    - [0.5, 0.6]
    - [0.6, 0.7]
    - [0.4, 0.6]

  # Optional: override T; if omitted, defaults are used in code
  T:
    - [-10, -6, -8, -4,-10, -6, -8, -4, -6, -8, -4,-10]
    - [-6, -2, -3, -2,-6, -2, -3, -2,-3, -2,-6, -2]
    - [-10, -6, -8, -4,-10, -6, -8, -4,-8, -4,-10, -6]
    - [-6, -2, -3, -2,-6, -2, -3, -2,-2,-6, -2, -3]
    - [0, 0, 0, 0,0, 0, 0, 0,0, 0, 0, 0]
