random_generator:
  train_n: 120
  test_n: 800
  J: 8
  I: 20
  p: 0.9
  lam_r: 2.0
  lam_w: 5.0
  c: [-14, -9, -20, -15, -4, -40, -18, -11, -13, -16, -17, -8, -9, -24, -10, -7, -12, -3, -4, -5]
  # c: [-14, -9, -20, -15, -4, -40, -20, -15, -15, -8, -9, -24, -10, -7, -12, -18, -11, -13, -16, -17]
  M: 1000
  epochs: 60
  seed: 2349

  # Intervals for regular regime
  h_int_r: [4000, 4500]
  q_ints_r:
    - [13, 15]
    - [13, 16]
    - [14, 17]
    - [14, 17]
    - [15, 17]
    - [14, 18]
    - [15, 19]
    - [18, 20]
    
  w_ints_r:
    - [0.8, 1]
    - [0.8, 1]
    - [0.9, 1]
    - [0.8, 1]
    - [0.85, 1]
    - [0.85, 1]
    - [0.9, 1]
    - [0.9, 1]

  # Intervals for extreme regime
  h_int_w: [400, 1000]
  q_ints_w:
    - [21, 25]
    - [21, 25]
    - [21, 23]
    - [19, 22]
    - [18, 20]
    - [18, 21]
    - [18, 20]
    - [22, 25]
  
  w_ints_w:
    - [0.5, 0.6]
    - [0.5, 0.6]
    - [0.6, 0.7]
    - [0.4, 0.6]
    - [0.55, 0.65]
    - [0.55, 0.65]
    - [0.6, 0.7]
    - [0.6, 0.7]
  

  # Optional: override T; if omitted, defaults are used in code
  T:
    - [-10, -6, -8, -4, -10, -6, -8, -4, -6, -8, -4, -10, -7, -9, -12, -8, -11, -13, -16, -17]
    - [-6, -2, -3, -2, -6, -2, -3, -2, -3, -2, -6, -2, -5, -3, -7, -4, -6, -5, -8, -9]
    - [-10, -6, -8, -4, -10, -6, -8, -4, -8, -4, -10, -6, -7, -9, -12, -8, -11, -13, -16, -17]
    - [-6, -2, -3, -2, -6, -2, -3, -2, -2, -6, -2, -3, -5, -3, -7, -4, -6, -5, -8, -9]
    - [0, -2, -3, -2, -2, -6, -2, -3, 0, 0, 0, 0,-1,-4, 0, -2, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 0, 0, 0, 0, -10, -6, -8, -4, 0, 0, 0, 0, -9, 0, 0]
    - [0, 0, 0, -1,-4, 0, -2, 0,0, 0, 0, 0, 0, 0, 0, 0, -5, 0, 0, 0]
    - [-6, -8, -4, -6, 0, 0, 0, 0, 0, -4, -6, -8, -4, -10, -7, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]